/**
 * [CF-169] Tool Sharing — Shareable Result Links
 * Encode tool output as shareable URL (base64 compressed) or downloadable PDF.
 * Exposed on window.CortexFreelancer.ToolShare
 */
(function () {
  'use strict';

  window.CortexFreelancer = window.CortexFreelancer || {};

  var PARAM_KEY = 'shared';
  var MAX_URL_LENGTH = 8000;
  var cssInjected = false;

  function escHtml(str) {
    var d = document.createElement('div');
    d.textContent = str || '';
    return d.innerHTML;
  }

  function injectCSS() {
    if (cssInjected) return;
    cssInjected = true;
    var style = document.createElement('style');
    style.textContent = [
      '.cf-share-bar { display: flex; gap: 8px; margin-top: 16px; flex-wrap: wrap; }',
      '.cf-share-btn { background: var(--bg-secondary, #f1f5f9); border: 1px solid var(--border-color, #e2e8f0); border-radius: 6px; padding: 6px 14px; cursor: pointer; font-size: 13px; display: flex; align-items: center; gap: 6px; transition: all 0.15s; }',
      '.cf-share-btn:hover { background: var(--bg-hover, #e2e8f0); }',
      '.cf-share-btn svg { width: 14px; height: 14px; }',
      '.cf-share-toast { position: fixed; bottom: 24px; left: 50%; transform: translateX(-50%); background: #1e293b; color: #fff; padding: 10px 20px; border-radius: 8px; font-size: 13px; z-index: 10000; opacity: 0; transition: opacity 0.2s; pointer-events: none; }',
      '.cf-share-toast.visible { opacity: 1; }'
    ].join('\n');
    document.head.appendChild(style);
  }

  // ── Encoding / Decoding ──

  function encodeData(data) {
    try {
      var json = JSON.stringify(data);
      return btoa(unescape(encodeURIComponent(json)));
    } catch (e) { return null; }
  }

  function decodeData(encoded) {
    try {
      var json = decodeURIComponent(escape(atob(encoded)));
      return JSON.parse(json);
    } catch (e) { return null; }
  }

  // ── URL sharing ──

  function generateShareURL(toolId, data) {
    var payload = { tool: toolId, data: data, ts: Date.now() };
    var encoded = encodeData(payload);
    if (!encoded) return null;

    var base = window.location.origin + window.location.pathname;
    var url = base + '?' + PARAM_KEY + '=' + encodeURIComponent(encoded);

    if (url.length > MAX_URL_LENGTH) {
      return null; // Too large for URL — suggest PDF instead
    }
    return url;
  }

  function readSharedData() {
    var params = new URLSearchParams(window.location.search);
    var encoded = params.get(PARAM_KEY);
    if (!encoded) return null;
    return decodeData(encoded);
  }

  // ── Clipboard ──

  function copyToClipboard(text, callback) {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(function () {
        if (callback) callback(true);
      }).catch(function () {
        fallbackCopy(text, callback);
      });
    } else {
      fallbackCopy(text, callback);
    }
  }

  function fallbackCopy(text, callback) {
    var ta = document.createElement('textarea');
    ta.value = text;
    ta.style.cssText = 'position:fixed;left:-9999px;';
    document.body.appendChild(ta);
    ta.select();
    try {
      document.execCommand('copy');
      if (callback) callback(true);
    } catch (e) {
      if (callback) callback(false);
    }
    document.body.removeChild(ta);
  }

  // ── PDF download ──

  function downloadAsPDF(toolId, data, title) {
    var content = typeof data === 'string' ? data : JSON.stringify(data, null, 2);
    var docTitle = title || toolId + ' — Results';

    // Generate a printable HTML page and trigger print-to-PDF
    var printWindow = window.open('', '_blank');
    if (!printWindow) return false;

    printWindow.document.write([
      '<!DOCTYPE html><html><head>',
      '<title>' + escHtml(docTitle) + '</title>',
      '<style>',
      'body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #1e293b; }',
      'h1 { font-size: 20px; border-bottom: 2px solid #6366f1; padding-bottom: 8px; }',
      'pre { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; white-space: pre-wrap; word-wrap: break-word; font-size: 13px; }',
      '.meta { color: #94a3b8; font-size: 12px; margin-top: 24px; }',
      '</style>',
      '</head><body>',
      '<h1>' + escHtml(docTitle) + '</h1>',
      '<pre>' + escHtml(content) + '</pre>',
      '<div class="meta">Generated by Cortex Freelancer &middot; ' + new Date().toLocaleDateString() + '</div>',
      '</body></html>'
    ].join(''));

    printWindow.document.close();
    setTimeout(function () { printWindow.print(); }, 300);
    return true;
  }

  // ── Toast notification ──

  function showToast(message) {
    var existing = document.querySelector('.cf-share-toast');
    if (existing) existing.remove();

    var toast = document.createElement('div');
    toast.className = 'cf-share-toast';
    toast.textContent = message;
    document.body.appendChild(toast);

    requestAnimationFrame(function () {
      toast.classList.add('visible');
    });

    setTimeout(function () {
      toast.classList.remove('visible');
      setTimeout(function () { toast.remove(); }, 300);
    }, 2500);
  }

  // ── Share bar UI ──

  function renderShareBar(container, toolId, getDataFn, options) {
    injectCSS();
    var el = typeof container === 'string' ? document.querySelector(container) : container;
    if (!el) return;

    var opts = options || {};
    var title = opts.title || toolId;

    var bar = document.createElement('div');
    bar.className = 'cf-share-bar';
    bar.innerHTML = [
      '<button class="cf-share-btn" data-action="copy-link" type="button">',
      '  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>',
      '  Copy Link',
      '</button>',
      '<button class="cf-share-btn" data-action="download-pdf" type="button">',
      '  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>',
      '  Download PDF',
      '</button>'
    ].join('');

    bar.addEventListener('click', function (e) {
      var btn = e.target.closest('[data-action]');
      if (!btn) return;

      var data = typeof getDataFn === 'function' ? getDataFn() : getDataFn;
      var action = btn.getAttribute('data-action');

      if (action === 'copy-link') {
        var url = generateShareURL(toolId, data);
        if (!url) {
          showToast('Data too large for URL — try PDF instead');
          return;
        }
        copyToClipboard(url, function (ok) {
          showToast(ok ? 'Link copied to clipboard!' : 'Failed to copy link');
        });
      }

      if (action === 'download-pdf') {
        var ok = downloadAsPDF(toolId, data, title);
        if (!ok) showToast('Pop-up blocked — please allow pop-ups');
      }
    });

    el.appendChild(bar);
  }

  window.CortexFreelancer.ToolShare = {
    renderShareBar: renderShareBar,
    generateShareURL: generateShareURL,
    readSharedData: readSharedData,
    downloadAsPDF: downloadAsPDF,
    copyToClipboard: copyToClipboard,
    encodeData: encodeData,
    decodeData: decodeData
  };
})();
